Birth_date:
  columns:
    pid: pat_id
    valueOutputDate: birthdate

Sex:
  columns:
    pid: pat_id
    valueAttributeIRI: sex

Diagnosis:
  columns:
    pid: pat_id
    valueAttributeIRI: diagnosis

    