   
class Template:

  template_model = dict(

    # Birthyear = dict(
    #   pid = None,
    #   event_id = None,
    #   comments = None,
    #   process_type = "http://purl.obolibrary.org/obo/NCIT_C142470",
    #   output_type = "http://purl.obolibrary.org/obo/NCIT_C70856",
    #   attribute_type = "http://purl.obolibrary.org/obo/NCIT_C83164",
    #   attribute_type2 = None,
    #   agent_id = None,
    #   input_type = None,
    #   target_type = None,
    #   activity_type = None,
    #   intensity_type = None,
    #   unit_type = None,
    #   agent_type = None,
    #   frequency_type = None,
    #   frequency_value = None,
    #   route_type = None,
    #   output_id = None,
    #   value_date = None,
    #   value_integer = None,
    #   value_string = None,
    #   value_float = None,
    #   value_datatype = "xsd:integer",
    #   age = None,
    #   startdate = None,
    #   enddate = None,
    #   uniqid = None,

    # ),

    Birthdate = dict(
      pid = None,
      event_id = None,
      comments = None,
      process_type = "http://purl.obolibrary.org/obo/NCIT_C142470",
      output_type = "http://purl.obolibrary.org/obo/NCIT_C70856",
      attribute_type = "http://purl.obolibrary.org/obo/NCIT_C68615",
      attribute_type2 = None,
      agent_id = None,
      substance_id = None,
      input_type = None,
      target_type = None,
      target_id = None,
      output_id = None,
      activity_type = None,
      intensity_type = None,
      unit_type = None,
      agent_type = None,
      frequency_type = None,
      frequency_value = None,
      route_type = None,
      concentration_value = None,
      value_date = None,
      value_integer = None,
      value_string = None,
      value_float = None,
      value_datatype = "xsd:date",
      age = None,
      startdate = None,
      enddate = None,
      uniqid = None,

    ),

    Deathdate = dict( 
      pid = None,
      event_id = None,
      comments = None,
      process_type = "http://purl.obolibrary.org/obo/NCIT_C142470",
      output_type = "http://purl.obolibrary.org/obo/NCIT_C70856",
      attribute_type = "http://purl.obolibrary.org/obo/NCIT_C70810",
      attribute_type2 = None,
      agent_id = None,
      substance_id = None,
      input_type = None,
      target_type = None,
      target_id = None,
      output_id = None,
      activity_type = None,
      intensity_type = None,
      unit_type = None,
      agent_type = None,
      frequency_type = None,
      frequency_value = None,
      route_type = None,
      concentration_value = None,
      value_date = None,
      value_integer = None,
      value_string = None,
      value_float = None,
      value_datatype = "xsd:date",
      age = None,
      startdate = None,
      enddate = None,
      uniqid = None,

    ),

    First_visit = dict(

      pid = None,
      event_id = None,
      comments = None,
      process_type = "http://purl.obolibrary.org/obo/NCIT_C142470",
      output_type = "http://purl.obolibrary.org/obo/NCIT_C70856",
      attribute_type = "http://purl.obolibrary.org/obo/NCIT_C164021",
      attribute_type2 = None,
      agent_id = None,
      substance_id = None,
      input_type = None,
      target_type = None,
      target_id = None,
      output_id = None,
      activity_type = None,
      intensity_type = None,
      unit_type = None,
      agent_type = None,
      frequency_type = None,
      frequency_value = None,
      route_type = None,
      concentration_value = None,
      value_date = None,
      value_integer = None,
      value_string = None,
      value_float = None,
      value_datatype = "xsd:date",
      age = None,
      startdate = None,
      enddate = None,
      uniqid = None,

    ),

    Sex = dict( 

      pid = None,
      event_id = None,
      comments = None,
      process_type = "http://purl.obolibrary.org/obo/NCIT_C142470",
      output_type = "http://purl.obolibrary.org/obo/NCIT_C70856",
      attribute_type = None,
      attribute_type2 = "http://purl.obolibrary.org/obo/NCIT_C28421",
      agent_id = None,
      substance_id = None,
      input_type = None,
      target_type = None,
      target_id = None,
      output_id = None,
      activity_type = None,
      intensity_type = None,
      unit_type = None,
      agent_type = None,
      frequency_type = None,
      frequency_value = None,
      route_type = None,
      concentration_value = None,
      value_date = None,
      value_integer = None,
      value_string = None,
      value_float = None,
      value_datatype = "xsd:string",
      age = None,
      startdate = None,
      enddate = None,
      uniqid = None,

    ),


    Status = dict(

      pid = None,
      event_id = None,
      comments = None,
      process_type = "http://purl.obolibrary.org/obo/NCIT_C142470",
      output_type = "http://purl.obolibrary.org/obo/NCIT_C70856",
      attribute_type = None,
      attribute_type2 = "http://purl.obolibrary.org/obo/NCIT_C166244",
      agent_id = None,
      substance_id = None,
      input_type = None,
      target_type = None,
      target_id = None,
      output_id = None,
      activity_type = None,
      intensity_type = None,
      unit_type = None,
      agent_type = None,
      frequency_type = None,
      frequency_value = None,
      route_type = None,
      concentration_value = None,
      value_date = None,
      value_integer = None,
      value_string = None,
      value_float = None,
      value_datatype = "xsd:string",
      age = None,
      startdate = None,
      enddate = None,
      uniqid = None,

    ),

    Diagnosis = dict(
      pid = None,
      event_id = None,
      comments = None,
      process_type = "http://purl.obolibrary.org/obo/NCIT_C18020",
      output_type = "http://purl.obolibrary.org/obo/NCIT_C70856",
      attribute_type = None,
      attribute_type2 = "http://purl.obolibrary.org/obo/NCIT_C2991",
      agent_id = None,
      substance_id = None,
      input_type = None,
      target_type = None,
      target_id = None,
      output_id = None,
      activity_type = None,
      intensity_type = None,
      unit_type = None,
      agent_type = None,
      frequency_type = None,
      frequency_value = None,
      route_type = None,
      concentration_value = None,
      value_date = None,
      value_integer = None,
      value_string = None,
      value_float = None,
      value_datatype = "xsd:string",
      age = None,
      startdate = None,
      enddate = None,
      uniqid = None,

    ),

    Symptom = dict(
      pid = None,
      event_id = None,
      comments = None,
      process_type = "http://purl.obolibrary.org/obo/NCIT_C18020",
      output_type = "http://purl.obolibrary.org/obo/NCIT_C70856",
      attribute_type = None,
      attribute_type2 = "http://purl.obolibrary.org/obo/NCIT_C100104",
      agent_id = None,
      substance_id = None,
      input_type = None,
      target_type = None,
      target_id = None,
      output_id = None,
      activity_type = None,
      intensity_type = None,
      unit_type = None,
      agent_type = None,
      frequency_type = None,
      frequency_value = None,
      route_type = None,
      concentration_value = None,
      value_date = None,
      value_integer = None,
      value_string = None,
      value_float = None,
      value_datatype = "xsd:string",
      age = None,
      startdate = None,
      enddate = None,
      uniqid = None,

    ),

    Symptoms_onset = dict(
      pid = None,
      event_id = None,
      comments = None,
      process_type= "http://purl.obolibrary.org/obo/NCIT_C142470",
      output_type = "http://purl.obolibrary.org/obo/NCIT_C70856",
      attribute_type2= "http://purl.obolibrary.org/obo/NCIT_C100104",
      attribute_type= "http://purl.obolibrary.org/obo/NCIT_C124353",
      agent_id = None,
      substance_id = None,
      input_type = None,
      target_type = None,
      target_id = None,
      output_id = None,
      activity_type = None,
      intensity_type = None,
      unit_type = None,
      agent_type = None,
      frequency_type = None,
      frequency_value = None,
      route_type = None,
      concentration_value = None,
      value_date = None,
      value_integer = None,
      value_string = None,
      value_float = None,
      value_datatype = "xsd:date",
      age = None,
      startdate = None,
      enddate = None,
      uniqid = None,

    ),

    Genetic = dict(
      pid = None,
      event_id = None,
      comments = None,
      process_type= "http://purl.obolibrary.org/obo/NCIT_C15709",
      output_type= "http://purl.obolibrary.org/obo/NCIT_C45766",
      attribute_type= "http://purl.obolibrary.org/obo/NCIT_C103223",
      attribute_type2 = None,
      agent_id = None,
      substance_id = None,
      input_type = None,
      target_type = "http://purl.obolibrary.org/obo/NCIT_C16612",
      target_id = None,
      activity_type = None,
      intensity_type = None,
      unit_type = None,
      agent_type = None,
      frequency_type = None,
      frequency_value = None,
      route_type = None,
      concentration_value = None,
      value_date = None,
      value_integer = None,
      value_string = None,
      value_float = None,
      value_datatype = "xsd:string",  
      age = None,
      startdate = None,
      enddate = None,
      uniqid = None,

    ),

    Consent_contacted = dict(
      pid = None,
      event_id = None,
      comments = None,
      process_type= "http://purl.obolibrary.org/obo/OBI_0000810",
      output_type = "http://purl.obolibrary.org/obo/OBIB_0000488",
      attribute_type= "http://purl.obolibrary.org/obo/NCIT_C25460",
      attribute_type2 = None,
      agent_id = None,
      substance_id = None,
      input_type = None,
      target_type = None,
      target_id = None,
      output_id = None,
      activity_type = None,
      intensity_type = None,
      unit_type = None,
      agent_type = None,
      frequency_type = None,
      frequency_value = None,
      route_type = None,
      concentration_value = None,
      value_date = None,
      value_integer = None,
      value_string = None,
      value_float = None,
      value_datatype = "xsd:string",
      age = None,
      startdate = None,
      enddate = None,
      uniqid = None,



    ),

    Consent_used = dict(
      pid = None,
      event_id = None,
      comments = None,
      process_type= "http://purl.obolibrary.org/obo/OBI_0000810",
      output_type = "http://purl.obolibrary.org/obo/DUO_0000001",
      attribute_type= "http://purl.obolibrary.org/obo/NCIT_C25460",
      attribute_type2 = None,
      agent_id = None,
      substance_id = None,
      input_type = None,
      target_type = None,
      target_id = None,
      output_id = None,
      activity_type = None,
      intensity_type = None,
      unit_type = None,
      agent_type = None,
      frequency_type = None,
      frequency_value = None,
      route_type = None,
      concentration_value = None,
      value_date = None,
      value_integer = None,
      value_string = None,
      value_float = None,
      value_datatype = "xsd:string",
      age = None,
      startdate = None,
      enddate = None,
      uniqid = None,

    ),

    Biobank = dict(
      pid = None,
      event_id = None,
      comments = None,
      process_type= "http://purl.obolibrary.org/obo/OMIABIS_0000061",
      output_type= "http://purl.obolibrary.org/obo/NCIT_C115570",
      attribute_type= "http://purl.obolibrary.org/obo/NCIT_C25429",
      attribute_type2 = None,
      agent_id = None,
      substance_id = None,
      input_type = None,
      target_type = None,
      target_id = None,
      activity_type = None,
      intensity_type = None,
      unit_type = None,
      agent_type = None,
      frequency_type = None,
      frequency_value = None,
      route_type = None,
      concentration_value = None,
      value_date = None,
      value_integer = None,
      value_string = None,
      value_float = None,
      value_datatype = "xsd:string",
      age = None,
      startdate = None,
      enddate = None,
      uniqid = None,

    ),

    Questionnaire = dict(
      pid = None,
      event_id = None,
      comments = None,
      process_type = "http://purl.obolibrary.org/obo/NCIT_C91102",
      output_type = "http://purl.obolibrary.org/obo/NCIT_C70856",
      attribute_type = "http://purl.obolibrary.org/obo/NCIT_C21007",
      attribute_type2 = None,
      agent_id = None,
      substance_id = None,
      input_type = None,
      target_type = None,
      target_id = None,
      output_id = None,
      activity_type = None,
      intensity_type = None,
      unit_type = None,
      agent_type = None,
      frequency_type = None,
      frequency_value = None,
      route_type = None,
      concentration_value = None,
      value_date = None,
      value_integer = None,
      value_string = None,
      value_float = None,
      value_datatype = "xsd:float",
      age = None,
      startdate = None,
      enddate = None,
      uniqid = None,

    ),

    Body_measurement = dict(
      pid = None,
      event_id = None,
      comments = None,
      process_type = "http://purl.obolibrary.org/obo/NCIT_C142470" ,
      output_type = "http://purl.obolibrary.org/obo/NCIT_C70856" ,
      attribute_type = None,
      attribute_type2 = None,
      agent_id = None,
      substance_id = None,
      input_type = None,
      target_type = None,
      target_id = None,
      output_id = None,
      activity_type = None,
      intensity_type = None,
      unit_type = None,
      agent_type = None,
      frequency_type = None,
      frequency_value = None,
      route_type = None,
      concentration_value = None,
      value_date = None,
      value_integer = None,
      value_string = None,
      value_float = None,
      value_datatype = "xsd:float" ,
      age = None,
      startdate = None,
      enddate = None,
      uniqid = None,

    ),


    Lab_measurement = dict(
      pid = None,
      event_id = None,
      comments = None,
      process_type = "http://purl.obolibrary.org/obo/NCIT_C25294" ,
      output_type = "http://purl.obolibrary.org/obo/NCIT_C70856" ,
      attribute_type = None,
      attribute_type2 = None,
      agent_id = None,
      substance_id = None,
      input_type = None,
      target_type = None,
      target_id = None,
      output_id = None,
      activity_type = None,
      intensity_type = None,
      unit_type = None,
      agent_type = None,
      frequency_type = None,
      frequency_value = None,
      route_type = None,
      concentration_value = None,
      value_date = None,
      value_integer = None,
      value_string = None,
      value_float = None,
      value_datatype= "xsd:float" ,
      age = None,
      startdate = None,
      enddate = None,
      uniqid = None,

    ),


    Imaging = dict(
      pid = None,
      event_id = None,
      comments = None,
      process_type = "http://purl.obolibrary.org/obo/NCIT_C17369",
      output_type =  "http://purl.obolibrary.org/obo/NCIT_C81289",
      attribute_type = "http://purl.obolibrary.org/obo/NCIT_C176708",
      attribute_type2 = None,
      agent_id = None,
      substance_id = None,
      input_type = None,
      target_type = None,
      target_id = None,
      output_id = None,
      activity_type = None,
      intensity_type = None,
      unit_type = None,
      agent_type = None,
      frequency_type = None,
      frequency_value = None,
      route_type = None,
      concentration_value = None,
      value_date = None,
      value_integer = None,
      value_string = None,
      value_float = None,
      value_datatype = "xsd:string" ,
      age = None,
      startdate = None,
      enddate = None,
      uniqid = None,

    ),


    Surgery = dict(
      pid = None,
      event_id = None,
      comments = None,
      process_type = "http://purl.obolibrary.org/obo/NCIT_C15329",
      output_type = None,
      attribute_type = None,
      attribute_type2 = None,
      agent_id = None,
      substance_id = None,
      input_type = None,
      target_type = None,
      target_id = None,
      output_id = None,
      activity_type = None,
      intensity_type = None,
      unit_type = None,
      agent_type = None,
      frequency_type = None,
      frequency_value = None,
      route_type = None,
      concentration_value = None,
      value_date = None,
      value_integer = None,
      value_string = None,
      value_float = None,
      value_datatype = "xsd:string" ,
      age = None,
      startdate = None,
      enddate = None,
      uniqid = None,


    ),


    Clinical_trial = dict(

      pid = None,
      event_id = None,
      comments = None,
      process_type = "http://purl.obolibrary.org/obo/NCIT_C71104" ,
      output_type=  "http://purl.obolibrary.org/obo/NCIT_C115575" ,
      attribute_type = None,
      attribute_type2 = "http://purl.obolibrary.org/obo/NCIT_C2991",
      agent_id = None,
      substance_id = None,
      input_type = None,
      target_type = None,
      target_id = None,
      output_id = None,
      activity_type = None,
      intensity_type = None,
      unit_type = None,
      agent_type = "http://purl.obolibrary.org/obo/NCIT_C16696" ,
      frequency_type = None,
      frequency_value = None,
      route_type = None,
      concentration_value = None,
      value_date = None,
      value_integer = None,
      value_string = None,
      value_float = None,
      value_datatype = "xsd:string",
      age = None,
      startdate = None,
      enddate = None,
      uniqid = None,


    ),

    Medication = dict(
      pid = None,
      event_id = None,
      comments = None,
      process_type = "http://purl.obolibrary.org/obo/NCIT_C70962",
      output_type = None ,
      attribute_type = None,
      attribute_type2 = None,
      agent_id = None,
      substance_id = None,
      input_type = None,
      target_type = None,
      target_id = None,
      output_id = None,
      activity_type = None,
      intensity_type = None,
      unit_type = None,
      agent_type = None,
      frequency_type = None,
      frequency_value = None,
      route_type = None,
      concentration_value = None,
      value_date = None,
      value_integer = None,
      value_string = None,
      value_float = None,
      value_datatype = "xsd:float",
      age = None,
      startdate = None,
      enddate = None,
      uniqid = None,

    )


  )